#!/bin/sh
#
echo "                                .__                 __         .__  .__         ";
echo "  ________  _  _______  ___.__. |__| ____   _______/  |______  |  | |  |        "; 
echo " /  ___/\ \/ \/ /\__  \<   |  | |  |/    \ /  ___/\   __\__  \ |  | |  |          ";
echo " \___ \  \     /  / __ \\___  | |  |   |  \\___ \  |  |  / __ \|  |_|  |__        ";
echo " ____  >  \/\_/  (____  / ____| |__|___|  /____  > |__| (____  /____/____/          ";
echo "    \/               \/\/              \/     \/            \/                      ";
echo "                                                                                  ";

#fix sudo

sudo -v
while true;do
  sudo -nv;sleep 1m
  kill -0 $$ 2>/dev/null || exit
done &

# clonacion de git
cd
git clone https://github.com/darch7/swaywm

# copy paste
cp -R swaywm/sway-solarized/config/* ~/.config/
mkdir ~/.themes 
mkdir ~/.icons 
cp -R swaywm/sway-solarized/walls/* ~/Pictures/
cp -R swaywm/.bashrc ~/
sudo cp -R /usr/share/icons/* ~/.icons
sudo cp -R /usr/share/themes/* ~/.themes
sudo flatpak override --filesystem=~/.icons
sudo flatpak override --filesystem=~/.themes

rpm-ostree install light mako neovim ranger sway swaylock waybar wofi lxpolkit kitty 




