#!/bin/sh
#
echo "                                .__                 __         .__  .__         ";
echo "  ________  _  _______  ___.__. |__| ____   _______/  |______  |  | |  |        "; 
echo " /  ___/\ \/ \/ /\__  \<   |  | |  |/    \ /  ___/\   __\__  \ |  | |  |          ";
echo " \___ \  \     /  / __ \\___  | |  |   |  \\___ \  |  |  / __ \|  |_|  |__        ";
echo " ____  >  \/\_/  (____  / ____| |__|___|  /____  > |__| (____  /____/____/          ";
echo "    \/               \/\/              \/     \/            \/                      ";
echo "                                                                                  ";

echo "Este instalador se intala sobre fedora silverblue ya que toma muchos
paquetes de ahi aprovechando la inmutabilidad del sistema y todas sus apps de
gnome"

#fix sudo

sudo -v
while true;do
  sudo -nv;sleep 1m
  kill -0 $$ 2>/dev/null || exit
done &

# clonacion de git
cd
echo "Clonando Git"
sleep 4
clear

git clone https://github.com/darch7/swaywm

clear
echo "Copy Paste arrancando en 3 seg"
sleep 3
clear

# copy paste
cp -R swaywm/sway-solarized/config/* ~/.config/
cp -R swaywm/.local/fonts ~/.local/share/
mkdir ~/.themes 
mkdir ~/.icons 
mkdir ~/.config/walls
cp -R swaywm/sway-solarized/walls/* ~/.config/walls
cp -R swaywm/.bashrc ~/

echo "Iniciando instalacion de themas y layareado de flatpak para temas"
sleep 4 
clear

sudo cp -R /usr/share/icons/* ~/.icons
sudo cp -R /usr/share/themes/* ~/.themes
sudo flatpak override --filesystem=~/.icons
sudo flatpak override --filesystem=~/.themes

echo "Eliminación de residuos"
sleep 4
clear

rm -rf swaywm
ls -la 
sleep 4
clear

echo "Instalcion de rpm-ostree de sway (rpms layareados) se instalaran
light,mako,ranger,sway,swaylock,wofi,lxpolkit y kitty"
sleep 5
clear
rpm-ostree cancel
rpm-ostree install light mako neovim ranger sway swaylock waybar wofi lxpolkit kitty 
clear
rpm-ostree status
sleep 4
clear

uname -a
sleep 3

echo "Sway Instalado"
sleep 3
systemctl reboot



